# Generated by Django 4.0.6 on 2022-07-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(verbose_name='Tanggal')),
                ('waktu', models.IntegerField(verbose_name='Waktu Patroli')),
                ('foto', models.ImageField(upload_to='static/upload/patroli', verbose_name='Foto Patroli')),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pegawai', models.CharField(max_length=30, verbose_name='Nama Pegawai')),
                ('jabatan', models.CharField(max_length=50, verbose_name='Jabatan')),
                ('nohp', models.CharField(max_length=20, verbose_name='No. Handphone')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_security', models.CharField(max_length=30, verbose_name='Nama Security')),
            ],
        ),
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(verbose_name='Tanggal')),
                ('nama', models.CharField(max_length=30, verbose_name='Nama Lengkap')),
                ('instansi', models.CharField(max_length=50, verbose_name='Instansi')),
                ('nohp', models.CharField(max_length=20, verbose_name='No. HP')),
                ('tujuan', models.CharField(max_length=150, verbose_name='Tujuan Berkunjung')),
                ('kondisi', models.CharField(max_length=90, verbose_name='Kondisi Kesehatan')),
                ('foto', models.ImageField(upload_to='static/upload/tamu', verbose_name='Foto Tamu')),
            ],
        ),
        migrations.CreateModel(
            name='Patroli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(verbose_name='Tanggal')),
                ('shift', models.CharField(max_length=10, verbose_name='Shift')),
                ('waktu', models.IntegerField(verbose_name='Waktu Patroli')),
                ('lokasi', models.CharField(max_length=200, verbose_name='Lokasi')),
                ('kondisi', models.CharField(max_length=200, verbose_name='Kondisi Kesehatan')),
                ('foto', models.ImageField(upload_to='static/upload/security patroli', verbose_name='Foto Security')),
                ('nama_security_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.security', verbose_name='Nama Security')),
            ],
        ),
    ]
