# Generated by Django 4.0.6 on 2022-07-27 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_apel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now=True, verbose_name='Tanggal')),
                ('detail_time', models.DateTimeField(verbose_name='Timestamp')),
                ('shift', models.CharField(max_length=10, verbose_name='Shift')),
                ('kondisi', models.CharField(max_length=200, verbose_name='Kondisi')),
                ('lokasi', models.CharField(max_length=100, verbose_name='Lokasi')),
                ('nama_security_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.security', verbose_name='Nama Security')),
            ],
        ),
    ]
