# Generated by Django 4.0.6 on 2022-07-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_cctv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('shift', models.CharField(max_length=10, verbose_name='Shift')),
                ('security1', models.CharField(max_length=30, verbose_name='Security 1')),
                ('security2', models.CharField(max_length=30, verbose_name='Security 1')),
            ],
        ),
    ]
