# Generated by Django 4.0.6 on 2022-07-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_cctv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='static/upload/jadwal', verbose_name='Jadwal Security')),
                ('periode', models.CharField(max_length=50, verbose_name='Periode')),
            ],
        ),
    ]
