# Generated by Django 4.0.6 on 2022-07-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='periode',
            field=models.DateField(verbose_name='Periode'),
        ),
    ]
