# Generated by Django 4.0.6 on 2022-07-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_jadwal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='security1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Security 1'),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='security2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Security 1'),
        ),
    ]
