# Generated by Django 4.0.6 on 2022-07-30 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_alter_schedule_periode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cctv',
            name='nama_security_id',
        ),
        migrations.AddField(
            model_name='cctv',
            name='nama_security',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Nama Secuirty'),
            preserve_default=False,
        ),
    ]
