# Generated by Django 4.0.6 on 2022-08-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_alter_schedule_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='foto',
            field=models.ImageField(upload_to='static/upload/jadwal', verbose_name='Jadwal Security'),
        ),
    ]
