# Generated by Django 4.0.6 on 2022-08-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_alter_foto_foto_alter_patroli_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='tanggal',
            field=models.DateField(verbose_name='Tanggal'),
        ),
    ]
