# Generated by Django 4.0.6 on 2022-08-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0014_alter_foto_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apel',
            name='tanggal',
            field=models.DateField(verbose_name='Tanggal'),
        ),
        migrations.AlterField(
            model_name='cctv',
            name='tanggal',
            field=models.DateField(verbose_name='Tanggal'),
        ),
        migrations.AlterField(
            model_name='patroli',
            name='tanggal',
            field=models.DateField(verbose_name='Tanggal'),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='tanggal',
            field=models.DateField(verbose_name='Tanggal'),
        ),
    ]
