# Generated by Django 4.0.6 on 2022-08-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0016_alter_patroli_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patroli',
            name='kondisi',
            field=models.CharField(max_length=200, verbose_name='Kondisi'),
        ),
    ]
